catname: "Next CPAN CI workflow"
description: "Automatically check & merge pull requests"
author: "atoomic"
inputs:
  stage:
    description: 'Main action to run'
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-pull-request"
  color: "blue"
