catname: "Next CPAN CI workflow"
description: "Automatically check & merge pull requests"
author: "atoomic"
inputs:
  stage:
    description: 'Main action to run'
    required: true
  conclusion:
    description: 'conclusion of the previous jobs: neutral, success, cancelled, timed_out, failure'
    required: false
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.stage }}
branding:
  icon: "git-pull-request"
  color: "blue"
