
git:
  user:
    email: 'actions@github.com'
    name: 'GitHub Play Action'

github:
  base_api_url: https://api.github.com
  org: next-cpan

  monitor:
    repo: Next-Monitor-Dashboard
    issues:      
      missing_token: 1
      slash_command: 2
      #no_response:

maintainers:
  file: .next/maintainers
  team: maintainers
  default_maintenance_teams:
    - "p5-bulk"
    - "p5-admins"

pull_requests:
  # how many days before an issue is automatically merged in
  stale_after_x_days: 7