
git:
  user:
    email: 'actions@github.com'
    name: 'GitHub Play Action'

github:
  base_api_url: https://api.github.com
  org: 'next-cpan'
  monitor_repo: 'next-monitor'

maintainers:
  file: .next/maintainers
  team: maintainers
  default_maintenance_teams:
    - "p5-bulk"
    - "p5-admins"

pull_requests:
  # how many days before an issue is automatically merged in
  stale_after_x_days: 7