name: 'testsuite'

on:
  push:
    branches:
      - "*"
    tags-ignore:
      - "*"
  pull_request:

jobs:
  perl_tester:
    runs-on: ubuntu-latest
    name: "perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.30"

    container:
      image: perldocker/perl-tester:${{ matrix.perl-version }}

    env:
       PERL_USE_UNSAFE_INC: 0
       AUTHOR_TESTING: 1
       AUTOMATED_TESTING: 1
       RELEASE_TESTING: 1
       PERL_CARTON_PATH: $GITHUB_WORKSPACE/local

    steps:
      - uses: actions/checkout@v2
      - name: uses install-with-cpanm
        uses: perl-actions/install-with-cpanm@v1.1
        with:
          cpanfile: "cpanfile"
          args: "--with-develop"
          sudo: false
      - name: t/*.t
        run: prove -Ilib -Ifatlib -v t/*.t
      - name: t/integration/*.t
        run: prove -Ilib -Ifatlib -v t/integration/*.t
